// Deterministic DOM tests, no browser control or game input.
import {createRequire} from 'node:module';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const require=createRequire(path.join(root,'runtime/ui-tests/package.json'));
const {JSDOM}=require('jsdom');
const html=await readFile(path.join(root,'web/index.html'),'utf8');
const realFetch=globalThis.fetch;
const base=process.env.UI_URL||'http://127.0.0.1:8766';
const bootstrap=await (await realFetch(base+'/api/bootstrap')).json();
const history=await (await realFetch(base+'/api/elixir/latest')).json();
const dustHistory=await (await realFetch(base+'/api/dust/latest')).json();
bootstrap.draft=null; // Test a fresh browser, not the user's existing database draft.
const dom=new JSDOM(html,{url:base,pretendToBeVisual:true});
globalThis.window=dom.window;globalThis.document=dom.window.document;globalThis.localStorage=dom.window.localStorage;
const requests=[];let savedConfig=null;let archived=false;
const storageId='b'.repeat(32);
const storageConfig={name:'重复配置',demands:[{profile:bootstrap.catalog.profiles[0].data}]};
globalThis.fetch=async(url,options={})=>{
  const body=options.body?JSON.parse(options.body):null;
  if(url==='/api/bootstrap')return Response.json(bootstrap);
  if(url==='/api/catalog')return Response.json(bootstrap.catalog);
  if(url==='/api/state')return Response.json({busy:false,can_resume:true,controller:'stopped',job:null,timings:[]});
  if(url==='/api/draft')return Response.json({revision:1,updated:Date.now()/1000,ignored:false});
  if(url==='/api/elixir/latest')return Response.json(history);
  if(url==='/api/dust/latest')return Response.json(dustHistory);
  requests.push({url,body});
  if(url==='/api/storage'){
    if(body?.action==='archive')archived=true;
    if(body?.action==='restore')archived=false;
    if(body?.action==='preview')return Response.json({preview:'test-preview',blocked:[],count:2,bytes:200});
    if(body)return Response.json({ok:true,bytes:200});
    const item={id:storageId,config:storageConfig,updated:Date.now()/1000,deleted:Date.now()/1000};
    return Response.json({directory:'test-runtime',sizes:{database:100,screenshots:200,records:100},configs:archived?[]:[item],trash:archived?[item]:[],blocked:[],count:2,bytes:200,protected_screenshots:1});
  }
  if(url==='/api/config'){
    savedConfig=body.config;
    return Response.json({id:'a'.repeat(32),config:body.config});
  }
  if(url.startsWith('/api/config/'))return Response.json(savedConfig);
  if(url==='/api/jobs')return Response.json({id:'test-job'}); // Never start a real game job in DOM tests.
  if(url==='/api/stop')return Response.json({stopped:true});
  throw Error('Unexpected request '+url);
};
const app=await import(pathToFileURL(path.join(root,'web/app.js')));
await window.__appReady;
assert.equal(app.importDraft(bootstrap.catalog.profiles[0].data).mode,'single');
const $=id=>document.getElementById(id);
if(history){assert.ok($('elixir-results').textContent.includes(history.character));assert.equal($('elixir-export').disabled,false);}
if(dustHistory){assert.ok($('dust-results').textContent.includes(dustHistory.character));assert.equal($('dust-export').disabled,false);}
const input=(id,value)=>{$(id).value=value;$(id).dispatchEvent(new window.Event('input',{bubbles:true}));};
const tick=()=>new Promise(r=>setTimeout(r,15));
const originalIds=JSON.parse(await readFile(path.join(root,'tests/ui_control_ids.json'),'utf8'));
for(const id of originalIds)assert.equal(document.querySelectorAll(`[id="${id}"]`).length,1,`Preserve ${id}`);
const ids=[...document.querySelectorAll('[id]')].map(x=>x.id);assert.equal(ids.length,new Set(ids).size);
document.querySelector('[data-page="guide"]').click();
assert.equal(window.location.hash,'#guide');assert.equal($('current-page-title').textContent,'使用指南');
assert.equal(document.querySelector('[data-page="guide"]').getAttribute('aria-current'),'page');
assert.ok($('guide-elixir').textContent.includes('剩余次数'));
assert.ok($('guide-dust').textContent.replace(/\s/g,'').includes('4/6'));
assert.ok($('guide-metrics').textContent.includes('目标内收益'));
document.querySelector('#page-guide [data-go="elixir"]').click();
assert.ok($('page-elixir').classList.contains('active'));
assert.equal($('elixir-budget').closest('form').id,'elixir-form');
assert.equal($('elixir-minimum').closest('form').id,'elixir-form');
const style=document.createElement('style');style.textContent=await readFile(path.join(root,'web/style.css'),'utf8');document.head.append(style);
assert.ok(style.sheet.cssRules.length>100);
assert.ok(style.textContent.includes('prefers-reduced-motion'));
assert.ok(!/@import|https?:\/\//.test(style.textContent));
window.ArtifactWorkbench.showPage('configure');
assert.equal(window.ArtifactWorkbench.serialize().mode,'single');
assert.equal(window.ArtifactWorkbench.serialize().demands.length,1);
assert.equal(document.querySelector('[data-weight="atk_"]').step,'0.01');
input('crit-cap','47');input('threshold','5');
assert.equal(window.ArtifactWorkbench.serialize().demands[0].profile.artifact_crit_rate_cap,47);
assert.equal(window.ArtifactWorkbench.serialize().demands[0].profile.threshold,.05);
assert.ok($('crit-cap').closest('label').textContent.includes('不是配装硬限制'));
$('mode-multi').click();$('add-demand').click();
input('character','测试角色');input('profile-name','第二套用途');
const prior=window.ArtifactWorkbench.getDraft().demands[1].id;
document.querySelectorAll('[data-move="-1"]')[1].click();
assert.equal(window.ArtifactWorkbench.getDraft().demands[0].id,prior);
assert.equal(window.ArtifactWorkbench.serialize().allocation,'priority');
$('custom-scenes').click();
assert.equal(window.ArtifactWorkbench.serialize().scenarios[0].demands.length,2);
$('save-config').click();await tick();
assert.equal(savedConfig.demands.length,2);
assert.equal(savedConfig.demands[0].profile.character,'测试角色');
assert.deepEqual(savedConfig.demands[0].profile.character_aliases,['测试角色']);
$('preview').click();await tick();await tick();
assert.ok(requests.some(r=>r.url==='/api/jobs'&&r.body.kind==='preview'));
assert.ok($('page-run').classList.contains('active'));
window.ArtifactWorkbench.showPage('configure');$('start').click();await tick();await tick();
const start=requests.find(r=>r.url==='/api/jobs'&&r.body.kind==='start');
assert.equal(start.body.fresh,true);
$('mode-single').click();
assert.equal(window.ArtifactWorkbench.serialize().demands.length,1);
assert.equal(window.ArtifactWorkbench.serialize().scenarios,null);
assert.equal(window.ArtifactWorkbench.serialize().demands[0].profile.character,'测试角色');
assert.equal(requests.filter(r=>r.url==='/api/jobs').length,2);
window.ArtifactWorkbench.showPage('elixir');
input('elixir-budget','7');input('elixir-minimum','0.25');
input('elixir-goal','35');$('elixir-compare').click();
$('elixir-quota').value='1';$('elixir-quota').dispatchEvent(new window.Event('change'));
$('elixir-objective').value='probability';$('elixir-objective').dispatchEvent(new window.Event('change'));
assert.equal(window.ArtifactWorkbench.getDraft().elixir.budget,7);
assert.equal(window.ArtifactWorkbench.getDraft().elixir.minimum_gain,.25);
assert.equal(window.ArtifactWorkbench.getDraft().elixir.remaining_by_set[window.ArtifactWorkbench.serialize().demands[0].profile.set_key],1);
assert.ok(document.querySelector('.elixir-model').textContent.includes('1/3'));
input('elixir-minimum','-1');document.querySelector('[data-advanced="elixir"]').open=false;
const countBeforeInvalid=requests.filter(r=>r.url==='/api/jobs').length;
$('elixir-calculate').click();await tick();
assert.equal(requests.filter(r=>r.url==='/api/jobs').length,countBeforeInvalid);
assert.equal(document.querySelector('[data-advanced="elixir"]').open,true);
input('elixir-minimum','0.25');
$('elixir-calculate').click();await tick();await tick();
const elixir=requests.find(r=>r.url==='/api/jobs'&&r.body.kind==='elixir');
assert.ok(elixir);assert.equal(elixir.body.demand_id,window.ArtifactWorkbench.serialize().demands[0].id);
assert.equal(savedConfig.elixir.budget,7);assert.equal(elixir.body.fresh,undefined);
assert.equal(savedConfig.elixir.compare_dust,true);assert.equal(savedConfig.demands[0].profile.resource_target_score,35);
assert.ok($('page-elixir').classList.contains('active'));
const action={slot:'circlet',main:'critDMG_',selected:['critRate_','atk_']};
const plan={actions:[action],cost:3,definitions:1,method:'enumerated',probability_lower:.96,probability_upper:.97,expected_gain_lower:1.07,expected_gain_upper:1.09};
const rendered=app.elixirResultHTML({character:'<img src=x onerror=alert(1)>',set_label:'测试套',demand_name:'测试',baseline:[28,28.1],options:{budget:4,minimum_gain:0},remaining:2,reserved_count:0,configuration:{crit_cap:47,equipment:'borrow',allocation:'independent'},scope:'当前库存',rankings:{expected_gain:[plan],probability:[plan],efficiency:[plan]}});
assert.ok(rendered.includes('96.00–97.00%'));assert.ok(rendered.includes('1.0700–1.0900'));
assert.ok(!rendered.includes('<img'));assert.ok(rendered.includes('&lt;img'));
const fragment=JSDOM.fragment(rendered);
assert.equal(fragment.querySelectorAll('.elixir-card.is-selected').length,1);
assert.equal(fragment.querySelector('.comparison-panel').tagName,'DETAILS');
assert.equal(fragment.querySelector('.comparison-panel').open,false);
document.querySelector('[data-page="dust"]').click();
assert.equal($('dust-goal').value,'35');
if(dustHistory){
 const item=dustHistory.inventory.find(a=>a.special==='ordinary');
 $('dust-item').value=item.id;$('dust-item').dispatchEvent(new window.Event('change'));
 assert.equal(document.querySelectorAll('[data-dust-base]').length,4);
 $('dust-meta-save').click();await tick();await tick();
 assert.ok(window.ArtifactWorkbench.getDraft().dust.metadata[item.fingerprint]);
 $('dust-meta-clear').click();await tick();await tick();
 assert.equal(window.ArtifactWorkbench.getDraft().dust.metadata[item.fingerprint],undefined);
}
$('dust-budget').value='33';$('dust-budget').dispatchEvent(new window.Event('change'));
$('dust-points').value='2';$('dust-points').dispatchEvent(new window.Event('change'));
$('dust-phase').value='2';$('dust-phase').dispatchEvent(new window.Event('change'));
assert.equal(window.ArtifactWorkbench.getDraft().dust.phase,2);
assert.ok($('dust-rule').textContent.includes('保底4次'));
$('dust-long-enabled').click();
assert.equal($('dust-long-days').disabled,false);
$('dust-long-days').value='60';$('dust-long-days').dispatchEvent(new window.Event('change'));
$('dust-long-daily_resin').value='120';$('dust-long-daily_resin').dispatchEvent(new window.Event('change'));
assert.equal(window.ArtifactWorkbench.getDraft().dust.longterm.days,60);
$('dust-calculate').click();await tick();await tick();
assert.ok(requests.some(r=>r.url==='/api/jobs'&&r.body.kind==='dust'));
assert.equal(savedConfig.dust.budget,33);assert.equal(savedConfig.dust.points,2);
assert.equal(savedConfig.dust.longterm.daily_resin,120);
const {forecastHTML}=await import(pathToFileURL(path.join(root,'web/longterm.js')));
const metric={estimate:[0,.1],mc95:[0,.2]};
const forecast=forecastHTML({options:{days:60,daily_resin:120,samples:128},scope:'期末重塑',limits:'测试',eligible_action_count:1,shortlist_count:1,
 horizons:[{days:60,expected_drops:383.4,natural_gain:metric,natural_probability:metric,slots:[{slot:'flower',gain:metric,probability:metric}],
 rankings:{efficiency:[{name:'<img src=x>',slot:'flower',cost:1,selected:['atk_'],expected_gain:metric,efficiency:metric,probability:metric}]}}]}, {atk_:'攻击'}, {flower:'花'}, '尘');
assert.ok(forecast.includes('每尘收益'));assert.ok(forecast.includes('抽样95%区间'));
assert.ok(forecast.includes('&lt;img'));assert.ok(!forecast.includes('<img'));
assert.equal(document.querySelectorAll('#page-dust button').length>0,true);
assert.ok(!$('page-dust').textContent.includes('自动重塑'));
window.confirm=()=>true;
window.ArtifactWorkbench.showPage('storage');await tick();await tick();
assert.ok($('storage-configs').textContent.includes('重复配置'));
document.querySelector('[data-config-select]').checked=true;
$('storage-delete-selected').click();await tick();await tick();
assert.ok(archived);assert.ok($('storage-trash').textContent.includes('恢复'));
document.querySelector('[data-restore]').click();await tick();await tick();assert.ok(!archived);
$('storage-preview').click();await tick();assert.equal($('storage-clean').disabled,false);
$('storage-clean').click();await tick();assert.ok(requests.some(r=>r.url==='/api/storage'&&r.body?.action==='clean'));
await window.ArtifactWorkbench.flushDraft();window.ArtifactWorkbench.dispose();dom.window.close();
console.log('DOM checks passed: 112 existing controls, guide navigation, accessible state, CSS parsing, advanced validation, saved settings, recommendation rendering and metadata editing. No game job launched.');
