const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function forecastForm(prefix,options,persist){
  const root=document.getElementById(prefix+'-forecast');
  root.innerHTML=`<summary>长期对照 · 继续刷取后，资源还值多少？</summary><label class="check-line"><input id="${prefix}-long-enabled" type="checkbox">计算自然刷取与期末单次资源收益</label><div class="fields two"><label>未来刷取天数<input id="${prefix}-long-days" type="number" min="0" max="365" step="1" required></label><label>每天投入该秘境的树脂<input id="${prefix}-long-daily_resin" type="number" min="0" max="1440" step="1" required></label><label>模拟规模<select id="${prefix}-long-samples"><option value="128">128条路径 · 快速预览</option><option value="512">512条路径 · 常规</option><option value="2048">2048条路径 · 较慢</option></select></label><label>每20树脂五星件数（模型假设）<input id="${prefix}-long-five_star_per_20" type="number" min="1" max="2" step="0.001" required></label></div><p class="small muted">默认最高等级普通秘境，目标套与另一套各50%，另一套可作散件。新掉落按全部培养至+20的潜力估计，未模拟5%停手。期末只用一次霜／尘；尘保底假设期间未被其他操作改变。保留原有即时收益排序。</p>`;
  const opts=()=>options().longterm??=({enabled:false,days:90,daily_resin:180,samples:512,seed:20261003,five_star_per_20:1.065});
  const render=()=>{const o=opts();for(const k of ['enabled','days','daily_resin','samples','five_star_per_20']){const e=document.getElementById(prefix+'-long-'+k);if(k==='enabled')e.checked=o[k];else{e.value=o[k];e.disabled=!o.enabled;}}if(o.enabled)root.open=true;};
  for(const k of ['enabled','days','daily_resin','samples','five_star_per_20'])document.getElementById(prefix+'-long-'+k).onchange=e=>{opts()[k]=k==='enabled'?e.target.checked:Number(e.target.value);persist();if(k==='enabled')render();};
  render();return render;
}
const format=(metric,scale=1)=>{const r=metric.estimate;return `${(r[0]*scale).toFixed(3)}–${(r[1]*scale).toFixed(3)}<br><small>${metric.mc95?`抽样95%区间 ${(metric.mc95[0]*scale).toFixed(3)}–${(metric.mc95[1]*scale).toFixed(3)}`:'未观测到提升；不将零样本方差解释为确定零收益'}</small>`;};
export function forecastHTML(r,STAT,SLOT,resource){
  if(!r)return '';
  return `<article class="panel"><span class="tag">有限周期预测 · 模拟对照</span><h2>自然刷取与长期资源收益</h2><p>${r.options.days}天 · 每天${r.options.daily_resin}树脂 · ${r.options.samples}条独立路径</p><p>${esc(r.scope)}</p><p class="small muted">“自然提升”由完整未来库存重新配装。“部位机会”只新增该部位，其余沿用今天库存；各部位结果不能相加。当前推荐是${r.eligible_action_count}种可用动作中筛出的${r.shortlist_count}种对照，未证明全局最佳。</p>${r.horizons.map(h=>`<details class="comparison-panel" ${h.days===r.options.days?'open':''}><summary>第${h.days}天 · 预计${h.expected_drops.toFixed(1)}件五星（含两套）</summary><p>不使用稀缺资源：整套平均提升 ${format(h.natural_gain)} 分；提升概率 ${format(h.natural_probability,100)}%</p><div class="table-wrap"><table><thead><tr><th>自然刷取的部位机会</th><th>改善整套的概率</th><th>平均整套提升</th></tr></thead><tbody>${h.slots.map(s=>`<tr><td>${SLOT[s.slot]}</td><td>${format(s.probability,100)}%</td><td>${format(s.gain)}分</td></tr>`).join('')}</tbody></table></div><h3>期末每${resource}收益优先 · 单次选择</h3><p class="small muted">衡量继续刷取后，资源还能补上多少差距。区间重叠时不要把名次当成确定结论；零命中不等于概率为零。</p><div class="table-wrap"><table><thead><tr><th>当前候选</th><th>成本</th><th>期末额外提升</th><th>每${resource}收益</th><th>额外提升概率</th></tr></thead><tbody>${h.rankings.efficiency.map(a=>`<tr><td>${esc(a.name||SLOT[a.slot])} · ${SLOT[a.slot]} ${esc(STAT[a.main]||'')}<br><small>${a.selected.map(k=>esc(STAT[k]||k)).join('＋')}${a.next_state?` · 本次保底${a.next_state.guarantee}`:''}</small></td><td>${a.cost}${resource}</td><td>${format(a.expected_gain)}</td><td>${format(a.efficiency)}</td><td>${format(a.probability,100)}%</td></tr>`).join('')||'<tr><td colspan="5">当前预算或次数下没有可执行候选，仅显示自然刷取对照。</td></tr>'}</tbody></table></div></details>`).join('')}<details><summary>预测边界与数学含义</summary><p>${esc(r.limits)}</p><p>收益估计范围来自当前显示值和未知底子；抽样区间另计。没有将“稀有度”转换成不透明的价值分，也没有用未来信息替今天决定尘的保留结果：本模型的重塑发生在刷取结束后。</p></details></article>`;
}
